#!/usr/bin/env bash
# Summary: Display the version of wheels
#
# Displays the version number of this wheels release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$WHEELS_DEBUG" ] && set -x

version="1.1.8"

if cd "$WHEELS_ROOT" 2>/dev/null; then
  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
  git_revision="${git_revision#v}"
fi

echo "wheels ${git_revision:-$version}"
