#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export WHEELS_DEBUG=1
  shift
fi

if [ -n "$WHEELS_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "wheels: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${WHEELS_ROOT}" ]; then
  WHEELS_ROOT="${HOME}/.wheels"
else
  WHEELS_ROOT="${WHEELS_ROOT%/}"
fi
export WHEELS_ROOT

if [ -z "${WHEELS_DIR}" ]; then
  WHEELS_DIR="$(pwd)"
else
  cd "$WHEELS_DIR" 2>/dev/null || {
    echo "wheels: cannot change working directory to \`$WHEELS_DIR'"
    exit 1
  } >&2
  WHEELS_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export WHEELS_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${WHEELS_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${WHEELS_HOOK_PATH}:${WHEELS_ROOT}/wheels.d:/usr/local/etc/wheels.d:/etc/wheels.d:/usr/lib/wheels/hooks"
for plugin_hook in "${WHEELS_ROOT}/plugins/"*/etc/wheels.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export WHEELS_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(wheels---version)\n$(wheels-help)" >&2
  ;;
"-v" )
  exec wheels---version
  ;;
* )
  command_path="$(command -v "wheels-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "wheels: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac